directories:
  sqldb_directory: data/sqldb.db


llm_config:
    agent_llm_system_role: "Given the following user question, corresponding SQL query, and SQL result, answer the user question.\n
    Question: {question}\n
    SQL Query: {query}\n
    SQL Result: {result}\n
    Answer: 
    "
    engine: "gemini-1.5-pro"
    temperature: 0.0

rag_config:
  collection_name: titanic_small
  top_k: 1